### ISSUE TITLE
Handle malformed data inputs (Safari bug)

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/ballotshare#65]
Safari doesn't support `<input type="date">`: https://caniuse.com/#feat=input-datetime

As a workaround we could attempt to parse formats other than `yyyy-mm-dd`.

**Comment by jacebrowning** [comment]
iOS Safari seems to submit dates in the format of "Jun 5, 2020".

**Comment by diiq** [comment]
Maybe consider a polyfill like https://github.com/brianblakely/nodep-date-input-polyfill ?
