### ISSUE TITLE
HTTPS Only

### ISSUE THREAD

**Issue by joshfriend** [citizenlabsgr/ballotshare#76]
The website currently supports both HTTP and HTTPS but only has a 301 redirect to the secure version on the main page. If a user visits the site via a non-https share link (as I did), the site will not direct them to a secure version if they want to look up their own info. Given that the info required to look up a ballot is enough PII to easily go find more PII about the user, this should probably _only_ operate over HTTPS.

**Comment by jacebrowning** [comment]
@joshfriend This should be fixed now.

http://share.michiganelections.io/elections/38/precincts/1209/ redirects to HTTPS. Please let us know if you see something different.

**Comment by joshfriend** [comment]
Perfect :+1:
